In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/sagnikpatra/uci-adult-census-data-dataset/adult_train.csv
/kaggle/input/datasets/sagnikpatra/uci-adult-census-data-dataset/adult_test.csv
/kaggle/input/datasets/zerotrace11/tech-company-dataset/tech_company_employee_data_1000.csv
/kaggle/input/datasets/iammustafatz/diabetes-prediction-dataset/diabetes_prediction_dataset.csv
/kaggle/input/datasets/shree1992/housedata/output.csv
/kaggle/input/datasets/shree1992/housedata/data.csv
/kaggle/input/datasets/shree1992/housedata/data.dat
/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
uci = pd.read_csv('/kaggle/input/datasets/sagnikpatra/uci-adult-census-data-dataset/adult_train.csv')
diabetes = pd.read_csv('/kaggle/input/datasets/iammustafatz/diabetes-prediction-dataset/diabetes_prediction_dataset.csv')
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
house = pd.read_csv('/kaggle/input/datasets/shree1992/housedata/data.csv')

# impute missing values of occupation column of uci dataset

In [4]:
uci.head()

,Age,Workclass,fnlwgt,Education,Education_Num,Martial_Status,Occupation,Relationship,Race,Sex,Capital_Gain,Capital_Loss,Hours_per_week,Country,Target
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [5]:
uci.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             32561 non-null  int64
 1   Workclass       30725 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   Education       32561 non-null  object
 4   Education_Num   32561 non-null  int64
 5   Martial_Status  32561 non-null  object
 6   Occupation      30718 non-null  object
 7   Relationship    32561 non-null  object
 8   Race            32561 non-null  object
 9   Sex             32561 non-null  object
 10  Capital_Gain    32561 non-null  int64
 11  Capital_Loss    32561 non-null  int64
 12  Hours_per_week  32561 non-null  int64
 13  Country         31978 non-null  object
 14  Target          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [6]:
uci.isnull().sum()/uci.shape[0]*100

Age               0.000000
Workclass         5.638647
fnlwgt            0.000000
Education         0.000000
Education_Num     0.000000
Martial_Status    0.000000
Occupation        5.660146
Relationship      0.000000
Race              0.000000
Sex               0.000000
Capital_Gain      0.000000
Capital_Loss      0.000000
Hours_per_week    0.000000
Country           1.790486
Target            0.000000
dtype: float64

In [7]:
uci=uci.dropna()
uci

,Age,Workclass,fnlwgt,Education,Education_Num,Martial_Status,Occupation,Relationship,Race,Sex,Capital_Gain,Capital_Loss,Hours_per_week,Country,Target
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [8]:
uci.isnull().sum()/uci.shape[0]*100

Age               0.0
Workclass         0.0
fnlwgt            0.0
Education         0.0
Education_Num     0.0
Martial_Status    0.0
Occupation        0.0
Relationship      0.0
Race              0.0
Sex               0.0
Capital_Gain      0.0
Capital_Loss      0.0
Hours_per_week    0.0
Country           0.0
Target            0.0
dtype: float64

In [9]:
uci['Occupation'].value_counts()

Occupation
Prof-specialty       4038
Craft-repair         4030
Exec-managerial      3992
Adm-clerical         3721
Sales                3584
Other-service        3212
Machine-op-inspct    1966
Transport-moving     1572
Handlers-cleaners    1350
Farming-fishing       989
Tech-support          912
Protective-serv       644
Priv-house-serv       143
Armed-Forces            9
Name: count, dtype: int64

# Outliers

# 1. find and mitigate(trimming and capping both) outliers on age column of diabetes dataset

In [10]:
diabetes.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [11]:
diabetes.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [12]:
diabetes['age'].describe()

count    100000.000000
mean         41.885856
std          22.516840
min           0.080000
25%          24.000000
50%          43.000000
75%          60.000000
max          80.000000
Name: age, dtype: float64

In [13]:
Q1 = diabetes['age'].quantile(0.25)
Q3 = diabetes['age'].quantile(0.75)
IQR = Q3 - Q1
print(Q1)
print(Q3)
print(IQR)

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

24.0
60.0
36.0
Lower bound: -30.0
Upper bound: 114.0

In [14]:
outliers =  diabetes[( diabetes['age'] < lower_bound) |( diabetes['age'] > upper_bound)]
print(outliers)
#NO outlier

Empty DataFrame
Columns: [gender, age, hypertension, heart_disease, smoking_history, bmi, HbA1c_level, blood_glucose_level, diabetes]
Index: []

# 2. find and mitigate(trimming and capping both) outliers on price column of house dataset

In [15]:
house.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [16]:
house.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [17]:
house['price'].describe()

count    4.600000e+03
mean     5.519630e+05
std      5.638347e+05
min      0.000000e+00
25%      3.228750e+05
50%      4.609435e+05
75%      6.549625e+05
max      2.659000e+07
Name: price, dtype: float64

In [18]:
house_Q1=house['price'].quantile(0.25)
house_Q3 = house['price'].quantile(0.75)
house_IQR = house_Q3 - house_Q1
print(house_Q1)
print(house_Q3)
print(house_IQR)

house_lower_bound = house_Q1- 1.5 * house_IQR
house_upper_bound =house_Q3 + 1.5 * house_IQR

print("Lower bound:", house_lower_bound)
print("Upper bound:", house_upper_bound)

322875.0
654962.5
332087.5
Lower bound: -175256.25
Upper bound: 1153093.75

In [19]:
house_outliers =  house[( house['price'] < house_lower_bound) |( house['price'] > house_upper_bound)]
print(house_outliers)

print("outlier :",house_outliers.shape)
#outlier 240

                     date         price  bedrooms  bathrooms  sqft_living  \
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650
11    2014-05-02 00:00:00  1.400000e+06       4.0       2.50         2920
14    2014-05-02 00:00:00  1.200000e+06       5.0       2.75         2910
99    2014-05-05 00:00:00  1.395000e+06       5.0       3.50         4010
122   2014-05-05 00:00:00  2.280000e+06       7.0       8.00        13540
...                   ...           ...       ...        ...          ...
4348  2014-05-05 00:00:00  2.199900e+06       4.0       1.50         1120
4350  2014-07-03 00:00:00  2.659000e+07       3.0       2.00         1180
4465  2014-06-05 00:00:00  2.560498e+06       3.0       2.50         1710
4467  2014-06-06 00:00:00  1.337044e+06       4.0       3.50         4280
4572  2014-07-02 00:00:00  1.288333e+06       6.0       4.50         3830

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
1         9050     2.0           0     4          5        3370
11        4000     1.5           0     0          5        1910
14        9480     1.5           0     0          3        2910
99        8510     2.0           0     1          5        2850
122     307752     3.0           0     4          3        9410
...        ...     ...         ...   ...        ...         ...
4348      5427     1.0           0     0          3        1120
4350      7793     1.0           0     0          4        1180
4465      1664     2.0           0     0          5        1300
4467      9583     2.0           0     0          3        4280
4572      4800     3.0           0     0          3        3050

      sqft_basement  yr_built  yr_renovated                   street  \
1               280      1921             0          709 W Blaine St
11             1010      1909          1988    3838-4098 44th Ave NE
14                0      1939          1969         3534 46th Ave NE
99             1160      1971             0       3930 NE Belvoir Pl
122            4130      1999             0         26408 NE 70th St
...             ...       ...           ...                      ...
4348              0      1969          2014  19009-19021 SE 266th St
4350              0      1992             0        12005 SE 219th Ct
4465            410      2003             0          2826 21st Ave W
4467              0      2005             0        1415 108th Ave SE
4572            780      1919          2004           2425 3rd Ave W

           city  statezip country
1       Seattle  WA 98119     USA
11      Seattle  WA 98105     USA
14      Seattle  WA 98105     USA
99      Seattle  WA 98105     USA
122     Redmond  WA 98053     USA
...         ...       ...     ...
4348  Covington  WA 98042     USA
4350       Kent  WA 98031     USA
4465    Seattle  WA 98199     USA
4467   Bellevue  WA 98004     USA
4572    Seattle  WA 98119     USA

[240 rows x 18 columns]
outlier : (240, 18)

In [20]:
#trimmed house price column
house_price_trimmed = house[
    (house['price'] >= house_lower_bound) &
    (house['price'] <= house_upper_bound)
]
house_price_trimmed

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.000000,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
2,2014-05-02 00:00:00,342000.000000,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.000000,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.000000,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
5,2014-05-02 00:00:00,490000.000000,2.0,1.00,880,6380,1.0,0,0,3,880,0,1938,1994,522 NE 88th St,Seattle,WA 98115,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,308166.666667,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,534333.333333,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,416904.166667,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,203400.000000,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,220600.000000,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

In [21]:
#capping 
house_capped = house.copy()

house_capped['price'] = house_capped['price'].clip(lower=house_lower_bound,upper=house_upper_bound)

In [22]:
capped_outliers = house_capped[
    (house_capped['price'] < house_lower_bound) |
    (house_capped['price'] > house_upper_bound)
]

len(capped_outliers)

0